version: "2"
services:

  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../:/usr/share/nginx/html
    ports:
      - "80:80"
    links:
      - php:php

  php:
    build: ./php
    restart: always
    expose:
      - "9000"
    links:
      - mysql
      - redis
    volumes:
      - ../:/usr/share/nginx/html
      - ./php/php.ini:/usr/local/etc/php/php.ini

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./mysql/my.cnf:/etc/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root!

  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    ports:
      - 8080:8080
 
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    command: redis-server --appendonly yes
